name: carinox
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - flask
  - requests
  - tqdm
  - scikit-learn
  - jinja2
  - yaml
  - pip:
      - transformers
      - torchmetrics
      - opencv-python-headless
      - huggingface-hub
      - sentencepiece
      - tensorboard
